-- Seed V5: Non-CS Skills (Medical, Law, Civil/Mechanical, Forensics, Modern Creator)

INSERT INTO skills (name) VALUES
  ('Anatomy'),
  ('Physiology'),
  ('Pharmacology'),
  ('Medical Ethics'),
  ('Patient Care'),
  ('Surgery Basics'),
  ('Structural Analysis'),
  ('AutoCAD'),
  ('Thermodynamics'),
  ('Fluid Mechanics'),
  ('Materials Science'),
  ('Project Management'),
  ('Constitutional Law'),
  ('Criminal Law'),
  ('Contract Law'),
  ('Legal Research'),
  ('Negotiation'),
  ('Corporate Law'),
  ('Cognitive Psychology'),
  ('Clinical Psychology'),
  ('Behavioral Analysis'),
  ('Counseling'),
  ('Research Methods'),
  ('Crime Scene Investigation'),
  ('Forensic Pathology'),
  ('DNA Analysis'),
  ('Fingerprint Analysis'),
  ('Criminalistics'),
  ('Digital Marketing'),
  ('Content Creation'),
  ('SEO'),
  ('Social Media Strategy'),
  ('Video Editing'),
  ('Copywriting'),
  ('Personal Finance'),
  ('Investing'),
  ('Entrepreneurship')
ON CONFLICT (name) DO NOTHING;

INSERT INTO courses (title, description, difficulty, duration_hours) VALUES
  ('Introduction to Human Anatomy', 'Foundational knowledge of human body structures and systems.', 'beginner', 20),
  ('Medical Ethics & Patient Care', 'Understanding the ethical principles of modern healthcare.', 'intermediate', 15),
  ('Basic Pharmacology', 'Study of drugs, their mechanisms, and therapeutic uses.', 'intermediate', 25),
  ('Structural Engineering Basics', 'Fundamentals of designing and analyzing physical structures.', 'beginner', 30),
  ('AutoCAD for Engineers', 'Master computer-aided design for civil and mechanical projects.', 'intermediate', 40),
  ('Thermodynamics & Fluid Mechanics', 'Core principles of energy, heat transfer, and fluid dynamics.', 'advanced', 35),
  ('Foundations of Criminal Law', 'Explore the legal principles governing criminal offenses.', 'beginner', 25),
  ('Contract Negotiation & Drafting', 'Learn to draft, review, and negotiate binding legal agreements.', 'intermediate', 20),
  ('Introduction to Cognitive Psychology', 'Study of mental processes such as attention, language, and memory.', 'beginner', 20),
  ('Clinical Counseling Techniques', 'Practical skills for therapeutic intervention and behavioral analysis.', 'advanced', 30),
  ('Crime Scene Investigation', 'Techniques for securing, documenting, and collecting evidence.', 'beginner', 25),
  ('Forensic Biology & DNA Analysis', 'Applying biological sciences to legal investigations.', 'advanced', 35),
  ('Digital Marketing Masterclass', 'Comprehensive guide to SEO, social media, and online growth.', 'beginner', 40),
  ('Content Creation & Video Editing', 'Build an audience through compelling storytelling and video production.', 'intermediate', 30),
  ('Personal Finance & Investing', 'Master wealth building, budgeting, and stock market fundamentals.', 'beginner', 15),
  ('Modern Entrepreneurship', 'From ideation to launch: building a startup in the 21st century.', 'intermediate', 25)
ON CONFLICT (title) DO NOTHING;

INSERT INTO course_skills (course_id, skill_id, is_prerequisite) VALUES
  ((SELECT id FROM courses WHERE title='Introduction to Human Anatomy'), (SELECT id FROM skills WHERE name='Anatomy'), true),
  ((SELECT id FROM courses WHERE title='Introduction to Human Anatomy'), (SELECT id FROM skills WHERE name='Physiology'), false),
  ((SELECT id FROM courses WHERE title='Medical Ethics & Patient Care'), (SELECT id FROM skills WHERE name='Medical Ethics'), true),
  ((SELECT id FROM courses WHERE title='Medical Ethics & Patient Care'), (SELECT id FROM skills WHERE name='Patient Care'), false),
  ((SELECT id FROM courses WHERE title='Basic Pharmacology'), (SELECT id FROM skills WHERE name='Pharmacology'), false),
  ((SELECT id FROM courses WHERE title='Structural Engineering Basics'), (SELECT id FROM skills WHERE name='Structural Analysis'), true),
  ((SELECT id FROM courses WHERE title='Structural Engineering Basics'), (SELECT id FROM skills WHERE name='Materials Science'), false),
  ((SELECT id FROM courses WHERE title='AutoCAD for Engineers'), (SELECT id FROM skills WHERE name='AutoCAD'), true),
  ((SELECT id FROM courses WHERE title='AutoCAD for Engineers'), (SELECT id FROM skills WHERE name='Project Management'), false),
  ((SELECT id FROM courses WHERE title='Thermodynamics & Fluid Mechanics'), (SELECT id FROM skills WHERE name='Thermodynamics'), true),
  ((SELECT id FROM courses WHERE title='Thermodynamics & Fluid Mechanics'), (SELECT id FROM skills WHERE name='Fluid Mechanics'), false),
  ((SELECT id FROM courses WHERE title='Foundations of Criminal Law'), (SELECT id FROM skills WHERE name='Criminal Law'), true),
  ((SELECT id FROM courses WHERE title='Foundations of Criminal Law'), (SELECT id FROM skills WHERE name='Legal Research'), false),
  ((SELECT id FROM courses WHERE title='Contract Negotiation & Drafting'), (SELECT id FROM skills WHERE name='Contract Law'), true),
  ((SELECT id FROM courses WHERE title='Contract Negotiation & Drafting'), (SELECT id FROM skills WHERE name='Negotiation'), false),
  ((SELECT id FROM courses WHERE title='Contract Negotiation & Drafting'), (SELECT id FROM skills WHERE name='Corporate Law'), false),
  ((SELECT id FROM courses WHERE title='Introduction to Cognitive Psychology'), (SELECT id FROM skills WHERE name='Cognitive Psychology'), true),
  ((SELECT id FROM courses WHERE title='Introduction to Cognitive Psychology'), (SELECT id FROM skills WHERE name='Research Methods'), false),
  ((SELECT id FROM courses WHERE title='Clinical Counseling Techniques'), (SELECT id FROM skills WHERE name='Clinical Psychology'), true),
  ((SELECT id FROM courses WHERE title='Clinical Counseling Techniques'), (SELECT id FROM skills WHERE name='Counseling'), false),
  ((SELECT id FROM courses WHERE title='Clinical Counseling Techniques'), (SELECT id FROM skills WHERE name='Behavioral Analysis'), false),
  ((SELECT id FROM courses WHERE title='Crime Scene Investigation'), (SELECT id FROM skills WHERE name='Crime Scene Investigation'), true),
  ((SELECT id FROM courses WHERE title='Crime Scene Investigation'), (SELECT id FROM skills WHERE name='Criminalistics'), false),
  ((SELECT id FROM courses WHERE title='Forensic Biology & DNA Analysis'), (SELECT id FROM skills WHERE name='Forensic Pathology'), true),
  ((SELECT id FROM courses WHERE title='Forensic Biology & DNA Analysis'), (SELECT id FROM skills WHERE name='DNA Analysis'), false),
  ((SELECT id FROM courses WHERE title='Digital Marketing Masterclass'), (SELECT id FROM skills WHERE name='Digital Marketing'), true),
  ((SELECT id FROM courses WHERE title='Digital Marketing Masterclass'), (SELECT id FROM skills WHERE name='SEO'), false),
  ((SELECT id FROM courses WHERE title='Digital Marketing Masterclass'), (SELECT id FROM skills WHERE name='Social Media Strategy'), false),
  ((SELECT id FROM courses WHERE title='Content Creation & Video Editing'), (SELECT id FROM skills WHERE name='Content Creation'), true),
  ((SELECT id FROM courses WHERE title='Content Creation & Video Editing'), (SELECT id FROM skills WHERE name='Video Editing'), false),
  ((SELECT id FROM courses WHERE title='Content Creation & Video Editing'), (SELECT id FROM skills WHERE name='Copywriting'), false),
  ((SELECT id FROM courses WHERE title='Personal Finance & Investing'), (SELECT id FROM skills WHERE name='Personal Finance'), true),
  ((SELECT id FROM courses WHERE title='Personal Finance & Investing'), (SELECT id FROM skills WHERE name='Investing'), false),
  ((SELECT id FROM courses WHERE title='Modern Entrepreneurship'), (SELECT id FROM skills WHERE name='Entrepreneurship'), true),
  ((SELECT id FROM courses WHERE title='Modern Entrepreneurship'), (SELECT id FROM skills WHERE name='Project Management'), false)
ON CONFLICT DO NOTHING;
