/**
 * questionBank.js — Comprehensive High-Yield Technical MCQ Question Bank
 * Categorized by skill focus with randomized options and deep conceptual explanations.
 */

export const QUESTION_BANK = {
  // ─── SQL & Data Warehousing ────────────────────────────────────────────────
  'SQL': [
    {
      skill_focus: 'SQL',
      difficulty: 'intermediate',
      question_text: 'In SQL, what is the key difference between the WHERE clause and the HAVING clause?',
      options: [
        'WHERE filters individual rows before aggregation, while HAVING filters grouped rows after GROUP BY is applied.',
        'HAVING is used exclusively for joining tables, whereas WHERE is used for sorting results.',
        'WHERE filters data after aggregation, while HAVING filters raw rows before aggregation.',
        'There is no functional difference; they are interchangeable aliases in ANSI SQL.'
      ],
      correct_option_index: 0,
      explanation: 'The WHERE clause filters raw table rows before any aggregations take place. The HAVING clause applies filters to aggregated summary values generated by GROUP BY.'
    },
    {
      skill_focus: 'SQL',
      difficulty: 'intermediate',
      question_text: 'Which SQL window function assigns consecutive integer ranks without skipping rank numbers when values tie?',
      options: [
        'RANK()',
        'ROW_NUMBER()',
        'DENSE_RANK()',
        'NTILE()'
      ],
      correct_option_index: 2,
      explanation: 'DENSE_RANK() assigns sequential ranks to tied values without leaving gaps (e.g. 1, 2, 2, 3), whereas RANK() skips subsequent rank numbers (e.g. 1, 2, 2, 4).'
    },
    {
      skill_focus: 'SQL',
      difficulty: 'advanced',
      question_text: 'When optimizing a slow analytical query involving a large fact table and multiple dimension tables, which strategy is most effective?',
      options: [
        'Replace all INNER JOINs with FULL OUTER JOINs',
        'Create clustered and composite B-Tree indexes on join and filter columns, and use CTEs or indexed views',
        'Remove all WHERE clauses and filter the dataset in memory on the client',
        'Convert all numerical primary keys to non-indexed text strings'
      ],
      correct_option_index: 1,
      explanation: 'Proper indexing on foreign key join columns and filter attributes avoids full table scans and drastically accelerates query execution in relational and dimensional databases.'
    }
  ],

  // ─── Pandas & Data Analysis ────────────────────────────────────────────────
  'Pandas': [
    {
      skill_focus: 'Pandas',
      difficulty: 'intermediate',
      question_text: 'In pandas, what is the primary operational difference between .loc[] and .iloc[]?',
      options: [
        '.loc[] is label-based indexing, whereas .iloc[] is zero-based integer positional indexing.',
        '.loc[] only works on Series, while .iloc[] only works on multi-dimensional DataFrames.',
        '.iloc[] includes both start and stop bounds, while .loc[] excludes the stop bound.',
        '.loc[] executes asynchronously in the background, while .iloc[] blocks the Python thread.'
      ],
      correct_option_index: 0,
      explanation: '.loc[] selects data using index and column labels (inclusive of both boundaries). .iloc[] selects data using purely integer position coordinates (exclusive of the stop boundary).'
    },
    {
      skill_focus: 'Pandas',
      difficulty: 'intermediate',
      question_text: 'When processing large DataFrames in Pandas, why is vectorized computation strongly preferred over iterating rows with for-loops or .apply()?',
      options: [
        'Vectorized operations execute low-level compiled C/Cython routines with SIMD CPU instructions, avoiding Python interpreter overhead.',
        'Iterating rows with for-loops automatically allocates unmanaged GPU memory.',
        '.apply() deletes unreferenced columns permanently from disk.',
        'Vectorized code prevents the garbage collector from running.'
      ],
      correct_option_index: 0,
      explanation: 'Pandas and NumPy vectorization executes in compiled C loops, processing entire memory contiguous arrays simultaneously rather than incurring Python object boxing/unboxing overhead per row.'
    }
  ],

  // ─── Python ────────────────────────────────────────────────────────────────
  'Python': [
    {
      skill_focus: 'Python',
      difficulty: 'intermediate',
      question_text: 'What happens when a Python function uses the "yield" keyword instead of "return"?',
      options: [
        'The function returns a generator object that produces values lazily on demand, preserving its local state between iterations.',
        'The function immediately terminates execution and writes the return value to disk.',
        'The function spawns an independent daemon thread in the operating system.',
        'The Python interpreter converts all variables inside the function into immutable tuples.'
      ],
      correct_option_index: 0,
      explanation: 'Functions containing yield return a generator iterator. When next() is called, execution resumes right after the yield statement, making generators memory efficient for large streams.'
    },
    {
      skill_focus: 'Python',
      difficulty: 'advanced',
      question_text: 'Why should mutable objects (like lists or dictionaries) never be used as default argument values in Python functions?',
      options: [
        'Default arguments are evaluated once when the function definition is executed, so all subsequent calls share the same mutated object.',
        'Python will throw a SyntaxError during bytecode compilation.',
        'Mutable default arguments cause memory leaks by bypassing reference counting.',
        'The function will be forced to run in single-threaded mode.'
      ],
      correct_option_index: 0,
      explanation: 'Python function defaults are evaluated once at definition time. Mutating a default list or dict inside the function modifies the persistent default object for all future invocations.'
    }
  ],

  // ─── Statistics & Data Analysis ────────────────────────────────────────────
  'Statistics': [
    {
      skill_focus: 'Statistics',
      difficulty: 'intermediate',
      question_text: 'In statistical hypothesis testing, what constitutes a Type I error?',
      options: [
        'Incorrectly rejecting a true null hypothesis (False Positive).',
        'Failing to reject a false null hypothesis (False Negative).',
        'Having a sample size smaller than 30 observations.',
        'Using a non-parametric test when data is normally distributed.'
      ],
      correct_option_index: 0,
      explanation: 'A Type I error occurs when the null hypothesis is true in reality, but you mistakenly reject it (finding an effect that does not exist, controlled by significance level alpha).'
    },
    {
      skill_focus: 'Statistics',
      difficulty: 'intermediate',
      question_text: 'When evaluating a machine learning model on a severely imbalanced dataset (e.g. 99% negative, 1% positive), which metric provides the most reliable signal?',
      options: [
        'Precision-Recall AUC (PR-AUC) or F1-Score',
        'Raw Accuracy Score',
        'Mean Absolute Error (MAE)',
        'R-squared ($R^2$)'
      ],
      correct_option_index: 0,
      explanation: 'On imbalanced datasets, raw accuracy is deceptive because a naive classifier predicting all negatives achieves 99% accuracy. Precision, Recall, and PR-AUC directly measure minority class discovery.'
    }
  ],

  // ─── Data Visualization & BI ───────────────────────────────────────────────
  'Data Visualization': [
    {
      skill_focus: 'Data Visualization',
      difficulty: 'intermediate',
      question_text: 'Which chart type is most appropriate for visualizing the statistical distribution and spread of continuous numerical data across multiple categorical groups?',
      options: [
        'Box Plot (Box-and-Whisker) or Violin Plot',
        'Pie Chart',
        'Stacked Area Chart',
        'Radar Chart'
      ],
      correct_option_index: 0,
      explanation: 'Box plots and violin plots display medians, interquartile ranges (IQR), probability densities, and outliers across groups without clutter or misleading proportion distortions.'
    }
  ],

  // ─── Machine Learning & Deep Learning ──────────────────────────────────────
  'Machine Learning': [
    {
      skill_focus: 'Machine Learning',
      difficulty: 'intermediate',
      question_text: 'What is the primary difference between L1 Regularization (Lasso) and L2 Regularization (Ridge)?',
      options: [
        'L1 adds the absolute value of coefficients and drives unimportant feature weights to exactly zero (feature selection), while L2 shrinks weights toward zero without setting them to zero.',
        'L2 can only be used with decision tree models, while L1 is used for neural networks.',
        'L1 increases model variance, while L2 increases model bias.',
        'L1 requires calculating matrix inverses, whereas L2 does not.'
      ],
      correct_option_index: 0,
      explanation: 'Lasso (L1 penalty) produces sparse models by zeroing out non-informative coefficients, acting as automated feature selection. Ridge (L2 penalty) smoothly shrinks coefficients to handle collinearity.'
    },
    {
      skill_focus: 'Deep Learning',
      difficulty: 'advanced',
      question_text: 'What fundamental problem does the Self-Attention mechanism solve in modern Transformer architectures compared to traditional RNNs/LSTMs?',
      options: [
        'It computes direct relationships between all token pairs simultaneously in $O(1)$ sequential operations, enabling parallel GPU training and capturing long-range dependencies.',
        'It eliminates the need for activation functions in neural networks.',
        'It completely removes the requirement for backpropagation.',
        'It converts floating-point weights into 1-bit integers during inference.'
      ],
      correct_option_index: 0,
      explanation: 'RNNs process tokens sequentially, creating bottlenecks for long sequences and gradient propagation. Transformers use scaled dot-product self-attention across the full sequence concurrently.'
    }
  ],

  // ─── Frontend & React ──────────────────────────────────────────────────────
  'React': [
    {
      skill_focus: 'React',
      difficulty: 'intermediate',
      question_text: 'What is the purpose of returning a cleanup function from a React useEffect hook?',
      options: [
        'To clean up side effects (such as unsubscribing from sockets, clearing intervals, or aborting fetch requests) when the component unmounts or before the effect re-runs.',
        'To immediately clear the browser cache and local storage.',
        'To reset the component state back to its initial default value.',
        'To force a synchronous re-render of child components.'
      ],
      correct_option_index: 0,
      explanation: 'React calls the cleanup function returned by useEffect before running the effect on next render or when the component unmounts, preventing memory leaks and orphaned subscriptions.'
    },
    {
      skill_focus: 'React',
      difficulty: 'advanced',
      question_text: 'When should you choose useCallback over regular inline functions in React?',
      options: [
        'When passing callback functions to memoized child components (React.memo) to prevent unnecessary re-renders caused by new function references.',
        'For every single function defined inside every component without exception.',
        'To automatically convert asynchronous functions into synchronous ones.',
        'To execute database queries directly from client components.'
      ],
      correct_option_index: 0,
      explanation: 'useCallback caches function definitions between renders. It is beneficial when passing functions to optimized child components that rely on shallow prop reference equality.'
    }
  ],

  // ─── Backend & APIs ────────────────────────────────────────────────────────
  'Backend Development': [
    {
      skill_focus: 'REST APIs',
      difficulty: 'intermediate',
      question_text: 'Which HTTP status code should a RESTful API return when a resource is successfully created via a POST request?',
      options: [
        '201 Created (often accompanied by a Location header pointing to the new resource)',
        '200 OK',
        '204 No Content',
        '202 Accepted'
      ],
      correct_option_index: 0,
      explanation: 'HTTP 201 Created is the standard status code indicating that a new resource was successfully instantiated as a result of the request, typically returning the created object or its URI.'
    },
    {
      skill_focus: 'Docker',
      difficulty: 'intermediate',
      question_text: 'What is the main advantage of utilizing Docker multi-stage builds in production deployment pipelines?',
      options: [
        'It separates the build environment (compilers, devDependencies) from the final runtime image, resulting in dramatically smaller and more secure production images.',
        'It allows a single container to run multiple different operating system kernels concurrently.',
        'It automatically scales containers across multiple cloud providers without Kubernetes.',
        'It encrypts container network traffic at the hardware level.'
      ],
      correct_option_index: 0,
      explanation: 'Multi-stage builds allow you to use heavy SDKs and toolchains in early stages, then copy only the compiled binaries/artifacts into a lean minimal base image (like Alpine or Distroless).'
    }
  ]
};

/**
 * Get distinct, randomized, high-quality MCQs for a given role and skill set
 */
export function getUniqueBankQuestions(skills = [], goal = 'Data Analyst', count = 5) {
  const selectedQuestions = [];
  const lowerGoal = goal.toLowerCase();

  // Determine relevant skill categories
  const targetKeys = [];
  if (lowerGoal.includes('analyst') || lowerGoal.includes('analytics')) {
    targetKeys.push('SQL', 'Pandas', 'Statistics', 'Data Visualization', 'Python');
  } else if (lowerGoal.includes('machine learning') || lowerGoal.includes('data scientist') || lowerGoal.includes('ai')) {
    targetKeys.push('Machine Learning', 'Python', 'Statistics', 'SQL', 'Deep Learning', 'Pandas');
  } else if (lowerGoal.includes('frontend') || lowerGoal.includes('react')) {
    targetKeys.push('React', 'Python', 'Backend Development');
  } else {
    targetKeys.push('SQL', 'Python', 'Backend Development', 'React', 'Statistics');
  }

  // Also include explicitly provided user skills
  for (const s of skills) {
    for (const k of Object.keys(QUESTION_BANK)) {
      if (s.toLowerCase().includes(k.toLowerCase()) && !targetKeys.includes(k)) {
        targetKeys.unshift(k);
      }
    }
  }

  // Pool questions from matching categories
  const pool = [];
  for (const key of targetKeys) {
    if (QUESTION_BANK[key]) {
      pool.push(...QUESTION_BANK[key]);
    }
  }

  // If pool is still small, add all questions
  if (pool.length < count) {
    Object.values(QUESTION_BANK).forEach(qList => pool.push(...qList));
  }

  // Shuffle pool
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  const picked = shuffled.slice(0, count);

  return picked.map((q, idx) => ({
    id: idx + 1,
    order_num: idx + 1,
    skill_focus: q.skill_focus,
    difficulty: q.difficulty,
    question_text: q.question_text,
    options: q.options,
    correct_option_index: q.correct_option_index,
    explanation: q.explanation,
  }));
}

